app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
	path('',views.index,name='index'),
	path('buat_kegiatan/',views.buat_kegiatan,name='buat_kegiatan'),
	path('buatKegiatan/',views.buatKegiatan,name='buatKegiatan'),
	path('daftar_kegiatan/',views.daftar_kegiatan,name='daftar_kegiatan'),
	path('buatDaftar/',views.buatDaftar,name='buatDaftar'),
	path('list_kegiatan/',views.list_kegiatan,name='list_kegiatan'),
]

story6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
]

app/models.py
from django.db import models

# Create your models here.
class DaftarKegiatan(models.Model):
	namaKegiatan = models.CharField(max_length = 200,default='')
	nama = models.CharField(max_length = 100, default='')


	

app/views.py
from django.shortcuts import render
from .models import DaftarKegiatan
# Create your views here.

def index(request):
	return render(request,'index.html')

def buat_kegiatan(request):
	return render(request,'buat_kegiatan.html')

def buatKegiatan(request):
	namaKegiatan = request.POST['namaKegiatan']
	infoKegiatan = DaftarKegiatan(namaKegiatan=namaKegiatan)
	infoKegiatan.save()
	return render(request,'buat_kegiatan.html')

def daftar_kegiatan(request):
	return render(request,'daftar_kegiatan.html')

# Buat daftar orang
def buatDaftar(request):
	nama = request.POST['nama']
	daftar = DaftarKegiatan(nama=nama)
	daftar.save()
	return render(request,'daftar_kegiatan.html')

def list_kegiatan(request):
	infoKegiatan = DaftarKegiatan.objects.all()
	kegiatan = {
		"info_kegiatan" : infoKegiatan
	}
	return render(request,'list_kegiatan.html',kegiatan)

app/templates/buat_kegiatan.html
{% extends 'header.html' %}
{% load static %}
{% block title %}Buat Kegiatan{% endblock %}

{% block content %}

<div class="container" style="margin-top: 2%">
	<h1 style="text-align: center;">Buat Kegiatan Baru</h1>
	<form action="/buatKegiatan/" class="was-validated" method="POST">
		{% csrf_token %}
	    <div class="form-group" style="margin-top: 5%">
	      <label for="namaKegiatan">Kegiatan :</label>
	      <input type="text" class="form-control" id="namaKegiatan" placeholder="Nama kegiatan" name="namaKegiatan" required>
	      <div class="valid-feedback">OK.</div>
	      <div class="invalid-feedback">Isi form terlebih dahulu.</div>
	    </div>
	    <div class="center_pos">
	    	<button type="submit" class="btn btn-primary" >Submit</button>
	    </div>
	</form>
</div>
{% endblock %}

app/templates/daftar_kegiatan.html
{% extends 'header.html' %}
{% load static %}
{% block title %}Form Kegiatan{% endblock %}


{% block content %}

<div class="container" style="margin-top: 2%">
	<h1 style="text-align: center;">Daftar Untuk Kegiatan</h1>
	<form action="/buatDaftar/" class="was-validated" method="POST">
		{% csrf_token %}
	    <div class="form-group" style="margin-top: 5%">
	      <label for="nama">Nama pendaftar: </label>
	      <input type="text" class="form-control" id="nama" placeholder="Nama" name="nama" required>
	      <div class="valid-feedback">OK.</div>
	      <div class="invalid-feedback">Isi form terlebih dahulu.</div>
	    </div>
	    <div class="center_pos">
	    	<button type="submit" class="btn btn-primary">Submit</button>
	    </div>
	</form>
</div>

{% endblock %}

app/templates/header.html
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'index.css' %}">
    <title>
    {% block title %}
    {% endblock %}
	</title>
  </head>
  <body>
  	<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
	  <ul class="navbar-nav">
	  	<li class="nav-item">
	  		<a class="nav-link" href="{% url 'app:index' %}">Halaman Utama</a>
	  	</li> 
	    <li class="nav-item">
	      <a class="nav-link" href="{% url 'app:buat_kegiatan' %}">Buat Kegiatan</a>
	    </li>
	    <li class="nav-item">
	      <a class="nav-link" href="{% url 'app:daftar_kegiatan' %}">Daftar Kegiatan</a>
	    </li>
	    <li class="nav-item">
	      <a class="nav-link" href="{% url 'app:list_kegiatan' %}">List Kegiatan</a>
	    </li>
	  </ul>
	</nav>

  	{% block content %}
  	{% endblock %}
  </body>

app/templates/index.html
{% extends 'header.html' %}
{% load static %}
{% block title %}Home{% endblock %}

{% block content %}

<div class = "container" style="margin-top: 2%">
	<h1 style="text-align: center;">Daftar atau Buat Kegiatan Anda</h1>
	<div class = "row" style="margin-top: 5%">
		<div class = "col-sm-6">
			<h3 style="text-align:center;">Buat Kegiatan Baru</h1>
			<div class="center_pos">
				<a href = "{% url 'app:buat_kegiatan' %}" class="btn btn-info" role="button" style="margin-top: 20px">Buat</a>
			</div>
		</div>
		<div class = "col-sm-6">
			<h3 style="text-align:center;">Daftar Kegiatan Baru</h1>
			<div class="center_pos">
				<a href = "{% url 'app:daftar_kegiatan' %}" class="btn btn-info" role="button" style="margin-top: 20px">Daftar</a>
			</div>
		</div>
	</div>
</div>

{% endblock %}

app/templates/list_kegiatan.html
{% extends 'header.html' %}
{% load static %}
{% block title %}Daftar Kegiatan{% endblock %}


{% block content %}
	<div class="container" style="margin-top: 5%">
		{% for kegiatan in info_kegiatan %}
			<h3 style="text-align: center;">{{ kegiatan.namaKegiatan }}</h3>
			<p style="text-align: center;">{{ kegiatan.nama }}
		{% endfor %}
{% endblock %}